config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#welcome'
  get '/about'  =>  'pages#about'
  get '/projects' => 'projects#index'
  get '/projects/:id' => 'projects#show', as: 'project'
  resource :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  def about
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Portfolio
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:100,300,500,700&display=swap", :rel => "stylesheet"}/
    %script{:src => "https://kit.fontawesome.com/972ee73f20.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    :css
      body {
        font-family: 'Roboto', sans-serif;
      }
    %script{:charset => "utf-8", :type => "text/javascript"}
  %body
    .header
      .container
        %nav.navbar.navbar-expand-lg.navbar-light
          %a.navbar-brand{:href => "/"} Home
          %button.navbar-toggler{"aria-controls" => "navbarColor03", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarColor03", "data-toggle" => "collapse", :type => "button"}
            %span.navbar-toggler-icon
          #navbarColor03.collapse.navbar-collapse
            %ul.navbar-nav.mr-auto
              %li.nav-item.active
                %a.nav-link{:href => "/projects"} Portfolio
              %li.nav-item.active
                %a.nav-link{:href => "#"} Blog
              %li.nav-item.active
                %a.nav-link{:href => "/about"} About
              %li.nav-item.active
                %a.nav-link{:href => "#"} Contact
            .autor
              %hr
                %h1 ~Piotr Skłodowski
    = yield
    .footer
      %ul
        %li
          %a{ :href => 'https://github.com/Zelears'}
            = image_tag("https://image.flaticon.com/icons/svg/25/25231.svg")
        %li
          %a{ :href => 'https://www.linkedin.com/in/piotr-sk%C5%82odowski-8181a818b/'}
            = image_tag("https://image.flaticon.com/icons/svg/1384/1384030.svg")
      .autor
        %h3 @ 2019 Piotr Skłodowski
    %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"}

app/views/pages/about.haml
.container
  -tag.each do |tag|
    .learning
      .example
        %h4 Example
        .card
          .card-text
            tag.example_text
      .description
        .title
          %h4
            tag.title
        .text
          %p
            tag.description_text
  .learning
    .example
      %h4 Example
      .card
        .card-text
          .display-1
            Display-1
          .display-2
            Display-2
          .display-3
            Display-3
          .display-4
            Display-4
    .description
      .title
        %h4
          Display Headings
      .text
        %p
          Display headings are used to stand out more than normal headings <span class='font-weight-bold'>
          (larger font-size and lighter font-weight)</span>,and there are four classes to choose
          from: .display-1, .display-2, .display-3, .display-4
  .learning
    .example
      %h4 Example
      .card
        .card-text
    .description
      .title
        %h4
      .text
        %p
  .learning
    .example
      %h4 Example
      .card
        .card-text
          %h1
            h1 heading
            %small
              secondary text
          %h2
            h2 heading
            %small
              secondary text
          %h3
            h3 heading
            %small
              secondary text
          %h4
            h4 heading
            %small
              secondary text
          %h5
            h5 heading
            %small
              secondary text
          %h6
            h6 heading
            %small
              secondary text
    .description
      .title
        %h4
          &ltsmall&gt
      .text
        %p
          In Bootstrap 4 the HTML <span class='font-weight-bold'> &ltsmall&gt </span>
          element is used to create a lighter, secondary text in any heading:
  .learning
    .example
      %h4 Example
      .card
        .card-text
          Use the mark element to
          %mark highlight
          text.
    .description
      .title
        %h4
          &ltmark&gt
      .text
        %p
          Bootstrap 4 will style the HTML &ltmark&gt element with a yellow background color and some padding:
  .learning
    .example
      %h4 Example
      .card
        .card-text
          The
          %abbr{:title=>'World Health Organization'} WHO
          was founded in 1948.
    .description
      .title
        %h4
          &ltabbr&gt
      .text
        %p
          Bootstrap 4 will style the HTML &ltabbr&gt element with a dotted border bottom:
  .learning
    .example
      %h4 Example
      .card
        .card-text
    .description
      .title
        %h4
      .text
        %p
  .learning
    .example
      %h4 Example
      .card
        .card-text
    .description
      .title
        %h4
      .text
        %p
  .learning
    .example
      %h4 Example
      .card
        .card-text
    .description
      .title
        %h4
      .text
        %p

app/views/pages/welcome.haml
.body
  .main-photo
    .container
      %h2
        Hello. My name is
        %span.highlight Piotr Skłodowski.
        I am passionate and hungry for knowledge
      %a{ :href => "/projects"}
        .btn.btn-secondary
          View my work

app/views/projects/index.haml
.container
  .row
    - @projects.each do |project|
      .col-md-6.text-dark
        =link_to project_path(project) do
          .project
            .thumbnail-header
              .thumbnail-header-btn.exit
              .thumbnail-header-btn.minimalize
              .thumbnail-header-btn.full_screen
            .portfolio-main-image
              -unless project.pictures.blank?
                -unless project.pictures.first.main_image.blank?
                  =image_tag project.pictures.first.main_image
            .card-body
              .title
                %h4
                  =project.title
              .portfolio-short-description
                %p.card-text.font-weight-light
                  =project.description

app/views/projects/show.haml
.container
  .row
    .col-xs-8
      .project-main-photo
        =image_tag url='lunares-logo.png'
        %hr
    .col-6
      .desc
        %ul
          %h2
            Top features
          %li
            Insane loading speed
          %li
            Custom professional Seo